import{a as h,i as a,S as g}from"./assets/vendor-Dpd1z_xS.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const m="48154537-527b84123da1832c7b7680c8e",y="https://pixabay.com/api/";async function f(t,e){const o=new URLSearchParams({key:m,q:t,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}),s=`${y}?${o}`;try{const r=await h.get(s);if(r.status!==200)throw new Error("Failed to fetch images");return{images:r.data.hits,totalHits:r.data.totalHits}}catch{throw new Error("Failed to fetch images")}}function p(t,e){const o=document.querySelector(".gallery");if(!o){console.error("Gallery element not found");return}if(t.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=t.map(({webformatURL:r,largeImageURL:n,tags:i,likes:c,views:l,comments:d,downloads:u})=>`
        <a href="${n}" class="gallery-item">
            <img src="${r}" alt="${i}" />
            <div class="info">
                <p><strong>Likes:</strong> <br> ${c}</p>
                <p><strong>Views:</strong> <br> ${l}</p>
                <p><strong>Comments:</strong> <br> ${d}</p>
                <p><strong>Downloads:</strong> <br> ${u}</p>
            </div>
        </a>
    `).join("");o.insertAdjacentHTML("beforeend",s)}function b(){const t=document.querySelectorAll(".gallery-item");if(t.length>0){const o=t[t.length-1].getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}function L(){const t=document.querySelector(".load-more-btn");if(!t)return;const e=document.querySelector(".loader")||v();t.style.display="none",e.classList.add("visible")}function S(){const t=document.querySelector(".loader"),e=document.querySelector(".load-more-btn");t&&t.classList.remove("visible"),e&&(e.style.display="block")}function v(){const t=document.createElement("div");return t.className="loader",document.querySelector(".gallery").insertAdjacentElement("afterend",t),t}function w(t,e){const o=document.querySelector(".load-more-btn"),s=document.querySelector(".end-message"),r=document.querySelector(".loader");o&&o.remove(),s&&s.remove(),r&&r.classList.remove("visible");const n=Math.ceil(document.querySelectorAll(".gallery-item").length/15);if(e===0)return;if(n*15>=e){t.insertAdjacentHTML("afterend",`
            <p class="end-message">We're sorry, but you've reached the end of search results.</p>
        `);return}t.insertAdjacentHTML("afterend",`
        <button type="button" class="load-more-btn">Load More</button>
    `)}class q{constructor(){this.currentPage=1,this.currentQuery="",this.lightbox=null,this.init()}init(){this.initializeElements(),this.initializeLightbox(),this.addEventListeners()}initializeElements(){if(this.searchButton=document.querySelector("#search-button"),this.searchInput=document.querySelector("#search-input"),this.gallery=document.querySelector(".gallery"),!this.searchButton||!this.searchInput||!this.gallery)throw new Error("Required elements not found")}initializeLightbox(){this.lightbox=new g(".gallery a")}addEventListeners(){this.searchButton.addEventListener("click",()=>this.handleSearch()),this.searchInput.addEventListener("keydown",e=>{e.key==="Enter"&&(e.preventDefault(),this.handleSearch())}),document.body.addEventListener("click",e=>{e.target.classList.contains("load-more-btn")&&this.handleLoadMore()})}async handleSearch(){const e=this.searchInput.value.trim();if(!e){a.warning({title:"Warning",message:"Please enter a search query."});return}this.currentQuery=e,this.currentPage=1,this.gallery.innerHTML="",await this.fetchAndRenderImages()}async handleLoadMore(){this.currentPage+=1,await this.fetchAndRenderImages(),b()}async fetchAndRenderImages(){try{L();const{images:e,totalHits:o}=await f(this.currentQuery,this.currentPage);p(e,o),this.lightbox.refresh(),this.currentPage===1&&w(this.gallery,o)}catch(e){a.error({title:"Error",message:e.message||"Failed to fetch images"})}finally{S()}}}document.addEventListener("DOMContentLoaded",()=>{try{new q}catch(t){console.error("Failed to initialize gallery:",t),a.error({title:"Error",message:"Failed to initialize the gallery"})}});
//# sourceMappingURL=index.js.map
