import{a as d,S as p,i as l}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const y="48154537-527b84123da1832c7b7680c8e",b="https://pixabay.com/api/";async function w(r){const o=`${b}?key=${y}&q=${r}&page=1&per_page=15&image_type=photo&orientation=horizontal&safesearch=true`;try{const n=await d.get(o);if(n.status!==200)throw new Error("Failed to fetch images");return n.data.hits}catch(n){throw console.error(n.message||"Something went wrong!"),new Error("Something went wrong!")}}let c=1;async function L(r){const s=`https://pixabay.com/api/?key=48154537-527b84123da1832c7b7680c8e&q=${r}&page=${c}&per_page=15&image_type=photo&orientation=horizontal&safesearch=true`;try{const e=await d.get(s);if(e.status!==200)throw new Error("Failed to fetch images");return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){console.error("Error fetching images:",e),iziToast.error({title:"Error",message:"Something went wrong while fetching images!"})}}function g(r,o){const n=document.querySelector(".gallery");if(r.length===0){iziToast.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=r.map(({webformatURL:e,largeImageURL:t,tags:a,likes:i,views:m,comments:h,downloads:f})=>`
        <a href="${t}" class="gallery-item">
            <img src="${e}" alt="${a}" />
            <div class="info">
                <p><strong>Likes:</strong> <br> ${i}</p>
                <p><strong>Views:</strong> <br> ${m}</p>
                <p><strong>Comments:</strong> <br> ${h}</p>
                <p><strong>Downloads:</strong> <br> ${f}</p>
            </div>
        </a>
    `).join("");n.insertAdjacentHTML("beforeend",s),$(n,o)}function S(){const r=document.querySelectorAll(".gallery-item");if(r.length>0){const n=r[r.length-1].getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}function E(){document.querySelector(".loader").classList.add("visible")}function u(){document.querySelector(".loader").classList.remove("visible")}function $(r,o){if(document.querySelector(".load-more-btn"))return;if(c*15>=o){r.insertAdjacentHTML("afterend",`
            <p class="end-message">We're sorry, but you've reached the end of search results.</p>
        `);return}r.insertAdjacentHTML("afterend",`
        <button class="load-more-btn">Load More</button>
    `),document.querySelector(".load-more-btn").addEventListener("click",async()=>{c+=1;const t="nature",{images:a,totalHits:i}=await L(t);g(a,i),S()})}document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector("#search-button"),o=document.querySelector("#search-input");if(!r||!o){console.error("Elements not found");return}let n=new p(".gallery a");const s=()=>{const t=o.value.trim();if(t===""){l.warning({title:"Warning",message:"Please enter a search query."});return}const a=document.querySelector(".gallery");a.innerHTML="",E(),w(t).then(i=>{u(),g(i),n.refresh()}).catch(i=>{u(),l.error({title:"Error",message:i.message})})},e=t=>{(t.type==="click"||t.key==="Enter")&&s()};r.addEventListener("click",e),o.addEventListener("keydown",e)});
//# sourceMappingURL=index.js.map
