import{S as f,i as a}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const g="48154537-527b84123da1832c7b7680c8e",m="https://pixabay.com/api/";function h(n){const o=`${m}?key=${g}&q=${n}&page=1&per_page=15&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(t=>{if(!t.ok)throw new Error("Failed to fetch images");return t.json()}).then(t=>t.hits).catch(t=>{throw console.error(t),new Error("Something went wrong!")})}function p(n){const o=document.querySelector(".gallery");if(n.length===0){iziToast.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const t=n.map(({webformatURL:i,largeImageURL:e,tags:r,likes:s,views:c,comments:d,downloads:u})=>`
        <a href="${e}" class="gallery-item">
            <img src="${i}" alt="${r}" />
            <div class="info">
                <p><strong>Likes:</strong> <br> ${s}</p>
                <p><strong>Views:</strong> <br> ${c}</p>
                <p><strong>Comments:</strong> <br> ${d}</p>
                <p><strong>Downloads:</strong> <br> ${u}</p>
            </div>
        </a>
    `).join("");o.insertAdjacentHTML("beforeend",t)}function y(){document.querySelector(".loader").classList.add("visible")}function l(){document.querySelector(".loader").classList.remove("visible")}document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector("#search-button"),o=document.querySelector("#search-input");if(!n||!o){console.error("Elements not found");return}let t=new f(".gallery a");const i=()=>{const r=o.value.trim();if(r===""){a.warning({title:"Warning",message:"Please enter a search query."});return}const s=document.querySelector(".gallery");s.innerHTML="",y(),h(r).then(c=>{l(),p(c),t.refresh()}).catch(c=>{l(),a.error({title:"Error",message:c.message})})},e=r=>{(r.type==="click"||r.key==="Enter")&&i()};n.addEventListener("click",e),o.addEventListener("keydown",e)});
//# sourceMappingURL=index.js.map
